# Generated by Django 5.2.5 on 2025-12-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product',
        ),
    ]
