# Generated by Django 5.2.5 on 2025-12-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_product_name_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='product',
            new_name='product_name',
        ),
    ]
