# Generated by Django 5.2.5 on 2025-12-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_name',
            new_name='product',
        ),
    ]
