# Generated by Django 5.2.5 on 2025-12-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_product_name_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_name',
        ),
    ]
