# Generated by Django 5.2.5 on 2025-12-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_product_cartitem_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
